default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_CABLE") %>

development:
  <<: *default
  channel_prefix: demo_swagger_docs_development

test:
  adapter: test

production:
  <<: *default
  channel_prefix: demo_swagger_docs_production
